version: 2
jobs:
  build:
    macos:
      xcode: "9.0.1"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip --output ghr.zip && unzip ghr.zip && ./ghr*/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete libangle32.${CIRCLE_BUILD_NUM} ./artifacts
