version: 2
jobs:
  build:
    macos:
      xcode: "9.0.1"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=`date`
            ./bin/darwin/amd64/github-release -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts
